### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-jsdoc#9]
As we now have automated publishing of jsdoc from master, shall we delete this repo?

**Comment by machikoyasuda** [comment]
yes

**Comment by machikoyasuda** [comment]
Updating the readme and archiving this repository

**Comment by machikoyasuda** [comment]
Disabled the github pages, so https://reactioncommerce.github.io/reaction-jsdoc/ is now dead!
